# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=5000)),
                ('time', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citys', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=64)),
                ('paytype', models.CharField(max_length=64)),
                ('renttype', models.CharField(max_length=64)),
                ('hometype', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=64)),
                ('decorade', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=500)),
                ('linkman', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('img', models.CharField(max_length=500)),
                ('features', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.HouseModel')),
            ],
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.CityModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='iocns')),
                ('sex', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='likemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.RegionModel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.CityModel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
        ),
    ]
